name: api-test-postman

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Newman CLI
        run: npm install -g newman

      - name: Install project dependencies
        working-directory: ${{ github.workspace }}/server
        run: npm install

      - name: Start backend server in background
        working-directory: ${{ github.workspace }}/server
        run: RUNNER_TRACKING_ID="" npm start &
      
      - name: Wait for backend to be ready
        run: |
          for i in {1..10}; do
            if nc -z localhost 3000; then
              echo "Backend is up!"
              break
            fi
            echo "Waiting for backend to be ready..."
            sleep 3
          done

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/My Collection.json" \
            --reporters cli,json \
            --reporter-json-export postman-report.json

      - name: Stop backend server (cleanup)
        if: always()
        run: |
          echo "Stopping backend server..."
          pkill -f "node" || true
